# Generated by Django 4.1.7 on 2023-06-09 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminWorks', '0006_blog_date_blog_viewcount'),
        ('users', '0002_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('disliked', models.BooleanField(default=False)),
                ('neutral', models.BooleanField(default=True)),
                ('blogId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_id', to='adminWorks.blog')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='users.user')),
            ],
        ),
    ]
